### ISSUE TITLE
The package is not from the official source

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/sam2-feedstock#4]
### Comment:

So this is generally the problem with `pypi` and facebook research. 
The pypi package is maintained by a an author who does not seem related to the SAM project on facebook
https://pypi.org/project/sam2/

Facebook research, to my knowledge, has not released anything on Pypi.
https://github.com/facebookresearch/sam2/issues/433

this is the nature of open source, but I think it is somewhat dangerous since the author does not list any modifications that they may or may not have done .

The "Version" number is also dubious 0.4.1 seems unrelated to anything from facebook. They claim they are at "1.0" but they also made a recent change in Oct with a release of sam 2.1 models
https://github.com/facebookresearch/sam2/blob/main/setup.py#L12

Honestly, I would prefer if we moved to the recipe that I have
https://github.com/conda-forge/staged-recipes/pull/27288

WIth the package name "sam-2" and not "sam2". The reason is that `pip` will list the installed package as `sam-2`.

**Comment by giswqs** [comment]
I agree. Facebook could have done better to release the official package on pypi. I really wanted to use sam2 and that sam2 package on pypi was the only one I could find and install successfully at the time. 

Since you are able to build from the official source now, please feel free to archive or rename this feedstock as you see fit.

**Comment by hmaarrfk** [comment]
ok i'll upload mine, then we can release a version "1" here that depends on "sam-2 >=1" and leave this as an abandonned feedstock.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender
