### ISSUE TITLE
how to install sam2 cuda variant?

### ISSUE THREAD

**Issue by rbavery** [conda-forge/sam2-feedstock#6]
### Comment:

Hello, apologies for my lack of familiarity with conda forge, I've searched docs and online but can't find an answer to the above question.

I'm trying to install the cuda variant of sam2 from this feedstock

If I try to specify the cuda build like [this example](https://github.com/opengeos/segment-geospatial?tab=readme-ov-file#install-from-conda-forge) it doesn't work

```
→ conda install "sam2=*=cuda*"

Looking for: ['sam2=[build=cuda*]']

conda-forge/noarch                                  17.7MB @  32.2MB/s  0.6s
conda-forge/linux-64                                40.6MB @  49.7MB/s  1.0s

Pinned packages:
  - python 3.11.*


Could not solve for environment specs
The following package could not be installed
└─ sam2 * cuda* does not exist (perhaps a typo or a missing channel).
```

I thought maybe `mamba install "sam2=*=*cuda*"` would capture it instead but that doesn't work either.

A search only shows one build is available.
```
→ conda search sam2
Loading channels: |
done
# Name                       Version           Build  Channel
sam2                           0.4.1 py310hf71b8c6_0  conda-forge
sam2                           0.4.1 py311hfdbb021_0  conda-forge
sam2                           0.4.1 py312h2ec8cdc_0  conda-forge
sam2                           0.4.1    pyh94de1ce_1  conda-forge
sam2                           1.0.0      hd8ed1ab_0  conda-forge
```

**Comment by hmaarrfk** [comment]
see https://github.com/conda-forge/sam-2-feedstock

sam2 points to it now.

```
conda install sam-2
```
should get you the right thing.

**Comment by hmaarrfk** [comment]
let me know if you have any other questions!

**Comment by rbavery** [comment]
Thank you!
